index:
    path: /
    controller: App\Controller\HomeController::index


dir:
    path: /dir
    controller: App\Controller\HomeController::DirNote

app_logout:
    path: /logout

api:
    path: /api
    controller: App\Controller\SecurityController::api